services:

  almacenamiento:
    build: ./almacenamiento
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DB}?retryWrites=true&w=majority&tls=true&authSource=admin
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}

  scraper:
    build:
      context: ./scraper
    environment:
      - URL_ALMACENAMIENTO=http://almacenamiento:8000/eventos
    depends_on:
      - almacenamiento

  filtrador:
    build: ./filtrador
    depends_on:
      - almacenamiento
    env_file:
      - .env
    command: python filtrador.py
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DB}?retryWrites=true&w=majority&tls=true&authSource=admin
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
    volumes:
      - ./filtrador/outputs:/app/outputs

  procesador:
    build: ./procesador
    container_name: procesador
    tty: true
    stdin_open: true
    depends_on:
      - filtrador
    volumes:
      - ./filtrador/outputs:/root/dataset
      - ./procesador/analisis_general.pig:/root/scripts/analisis_general.pig
      - ./resultados_pig:/root/results

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.encryptedSavedObjects.encryptionKey=4776220a0b0bb2bf41a5ae02e158133e
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  indexador:
    build: ./elasticsearch
    depends_on:
      - elasticsearch
      - filtrador
    volumes:
      - ./filtrador/outputs:/app/outputs
      - ./resultados_pig:/app/../resultados_pig
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
    command: python indexador.py
    networks:
      - elastic

  redis:
    image: redis:latest
    command: redis-server --maxmemory 10gb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cache:
    build: ./cache
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - almacenamiento
      - elasticsearch
    environment:
      - TTL_CACHE=86400
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elastic

networks:
  elastic:

volumes:
  redis_data:
